openapi: 3.0.0
info:
  title: OpenAPI Specification to Room in a Smart Home
  description: To get the list of connected devices in a Room in the Smart Home
  version: 0.1.9
  
servers: 
  - url: hhtp://getapi.roomdevices.com/v1
    
    
paths: 
  /devices/{roomId}:
    get:
      summary: Returns list of connected devices in a room of given ID.
      description: To return a list of all connected devices in a Room in a Smart Home
      parameters:
      - name: roomId
        in: path
        required: true
        schema: 
          type: string
          format: int64
          minimum: 1
      responses:
        '200': 
          description: A room object
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        '400':
          description: The specified roomId is invalid