openapi: 3.0.0
info:
  title: OpenAPI Specification to change current status of the Device
  description: To change the current status of the device in a Room in the Smart Home
  version: 0.1.9
  
servers: 
  - url: hhtp://getapi.devicestatus.com/v1
    
    
paths: 
  /room/{roomId}/devices/{deviceId}/status:
    put:
      summary: Update device status
      requestBody:
        required: true
        content:
          text/plain:
            schema:
              type: string
      
      parameters:
      - name: roomId
        in: path
        required: true
        schema: 
          type: string
      - name: deviceId
        in: path
        required: true
        schema:
          type: string
      responses:
        '200': 
          description: A device object
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        '400':
          description: The specified roomId or deviceId is invalid